version: '3'

services:
  app:
    build: ./node-app
    container_name: app_nodejs
    networks:
      - traefik
    labels:
      - "traefik.http.routers.nodejs-app.rule=Host(`nodejsapp.docker.localhost`)"
      - "traefik.http.services.nodejs-app.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
